CREATE TABLE contact_information
(
	id                 BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	full_name          TEXT   NOT NULL,
	phone_number       TEXT   NOT NULL,
	email_address      TEXT   NOT NULL,
	message            TEXT   NOT NULL,
	property           TEXT   NOT NULL
);
